In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline

In [15]:
X= -2 * np.random.rand(100,2)
X1 = 1 + 2 * np.random.rand(50,2)
X[50:100, :] = X1
#plt.scatter(X[ : , 0], X[ :, 1], s = 50, c = ‘b’)
plt.show()


In [5]:
from sklearn.cluster import KMeans
Kmean = KMeans(n_clusters=2)
Kmean.fit(X)

KMeans(n_clusters=2)

In [10]:
#KMeans(algorithm=’auto’, copy_x=True, init=’k-means++’, max_iter=300
# n_clusters=2, n_init=10, n_jobs=1, precompute_distances=’auto’,
 #random_state=None, tol=0.0001, verbose=0
       

In [8]:
Kmean.cluster_centers_

array([[-1.0349426 , -0.85341848],
       [ 1.99978187,  2.06526619]])

In [16]:
#plt.scatter(X[ : , 0], X[ : , 1], s =50, c=’b’)
#plt.scatter(-0.94665068, -0.97138368, s=200, c=’g’, marker=’s’)
#plt.scatter(2.01559419, 2.02597093, s=200, c=’r’, marker=’s’)
#plt.show()

In [17]:
Kmean.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [18]:
sample_test=np.array([-3.0,-3.0])
second_test=sample_test.reshape(1, -1)
Kmean.predict(second_test)

array([0], dtype=int32)

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline
X= -2 * np.random.rand(100,2)
X1 = 1 + 2 * np.random.rand(50,2)
X[50:100, :] = X1
#plt.scatter(X[ : , 0], X[ :, 1], s = 50, c = ‘b’)
plt.show()
from sklearn.cluster import KMeans
Kmean = KMeans(n_clusters=2)
Kmean.fit(X)
Kmean.cluster_centers_
#plt.scatter(X[ : , 0], X[ : , 1], s =50, c=’b’)
#plt.scatter(-0.94665068, -0.97138368, s=200, c=’g’, marker=’s’)
#plt.scatter(2.01559419, 2.02597093, s=200, c=’r’, marker=’s’)
plt.show()
Kmean.labels_
sample_test=np.array([-3.0,-3.0])
second_test=sample_test.reshape(1, -1)
Kmean.predict(second_test)

array([1], dtype=int32)